name: publish-plugin

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  bump-version:
    runs-on: ubuntu-latest
    outputs:
      new-version: ${{ steps.bump.outputs.newVersion }}
      new-tag: ${{ steps.bump.outputs.newTag }}

    steps:
      - uses: actions/checkout@v3

      - name: Bump version
        id: bump
        uses: phips28/gh-action-bump-version@v11.0.7
        with:
          tag-prefix: 'v'
          commit-message: 'ci: bump version to {{version}}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-plugin:
    runs-on: ubuntu-latest
    needs: bump-version
    env:
      WINDY_API_KEY: '${{ secrets.WINDY_API_KEY }}'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint --if-present

      - name: Run tests
        run: npm test --if-present

      - name: Build
        run: npm run build

      - name: Publish Plugin
        if: success()
        run: |
          VERSION="${{ needs.bump-version.outputs.new-version }}"
          echo "Publishing version $VERSION"

          if [ -z "$VERSION" ]; then
            echo "âŒ ERROR: VERSION is empty" >&2
            exit 1
          fi

          cd dist

          jq --arg ver "$VERSION" '.version = $ver' plugin.json > plugin.tmp && mv plugin.tmp plugin.json

          echo "{\"repositoryName\": \"${{ github.repository }}\", \"commitSha\": \"${{ github.sha }}\", \"repositoryOwner\": \"${{ github.repository_owner }}\"}" > /tmp/plugin-info.json
          jq -s '.[0] * .[1]' plugin.json /tmp/plugin-info.json > plugin.tmp && mv plugin.tmp plugin.json

          echo "Creating plugin archive..."
          tar cf ../plugin.tar .

          echo "Publishing plugin..."
          curl -s --fail-with-body -XPOST 'https://node.windy.com/plugins/v1.0/upload' \
              -H "x-windy-api-key: ${WINDY_API_KEY}" \
              -F "plugin_archive=@../plugin.tar"


